### ISSUE TITLE
Add style to the task form errors

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/myntenance#2]
Maybe red text, a bit smaller... open to suggestions :)

![image](https://github.com/user-attachments/assets/1970e199-d3b3-4f79-8445-7cfa9eefe72d)

**Comment by Anujjoshi3105** [comment]
Hi @Balastrong ,

I’d like to work on styling the task form error messages as mentioned in issue #2.
![image](https://github.com/user-attachments/assets/f8965100-478c-48a7-a3bb-ad49f5bf3338)
