### ISSUE TITLE
Task table: add time on hover to createdAt date

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/myntenance#20]
There's not enough room for date + time, an idea could be to add the time (or full date) on hover to the createdAt cells in the task table

![image](https://github.com/user-attachments/assets/12cd7e14-b8a4-497a-b886-fa4a4581e6c7)

**Comment by nmarmugi** [comment]
Hi Leonardo, can i take this one?

**Comment by Balastrong** [comment]
Done in #32
