### ISSUE TITLE
Add a loader to the delete button

### ISSUE THREAD

**Issue by emanuelegurini** [Balastrong/myntenance#25]
Add a loader to the delete button

**Comment by ZeeshanMukhtar1** [comment]
Hi @Balastrong , 
cound u please assign me this issue !

**Comment by Balastrong** [comment]
It has been implemented in #30 I think, closing this issue.

Feel free to pick another one or create an issue if you have feature ideas, I'll be happy to assign one to you @ZeeshanMukhtar1 :)
