### ISSUE TITLE
Button to remove sorting from table columns

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/myntenance#3]
We can now sort asc or desc, we should add a new button to remove sorting.

![image](https://github.com/user-attachments/assets/5b57d66b-b923-4e64-9226-b6c0b6709ba0)

**Comment by nmarmugi** [comment]
Hi Leonardo, nice to meet you, I'm Nicola. What do you mean by adding a button that removes the sorting? I tried a bit, and even if we reset the fetch for ascending or descending, we would still have an ascending order. What do you mean? Can you explain it to me better? Thanks!

**Comment by Balastrong** [comment]
Hey Nicola!

As of today each column has two buttons, one that sets ascending sorting and the other that sets descending. The buttons are defined here:
https://github.com/Balastrong/myntenance/blob/7ab46567c281167f108c50a9a58e4dbdb36e6d98/src/components/ui/data-table/data-table-column-header.tsx#L61-L84

Once you click one, there's no way to remove sorting for that column (other than applying sorting to another column).

The new button should simply clear sorting on that column.

**Comment by Balastrong** [comment]
Done in #31
