### ISSUE TITLE
"Create more" checkbox

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/myntenance#44]
Add a checkbox on the task create modal "Create more"

![image](https://github.com/user-attachments/assets/2cfa713f-6c2c-4778-a8f3-0010d8de7eaa)

Having the checkbox enabled when clicking Create resets the form instead of closing the modal, making it quicker to create a new task.

**Comment by Joshua-Vankayalapati** [comment]
Hello Balastrong,

Check this gif.
The modal opens and extends with the additional input fields when 'Create More' is checked, and the form behaves as expected when clicking 'Create'.

![more+](https://github.com/user-attachments/assets/94a15a7b-39c9-45fc-8300-a8c40cb2ef4a)

Let me know, if this is the kind of functionality you're looking for.

Regards,
Josh

**Comment by Balastrong** [comment]
Hey Josh!

There aren't more fields to be shown, the only behavior with the flag enabled is as described in the issue: the modal does not close and the form resets so you can create one more issue quickly.

**Comment by Joshua-Vankayalapati** [comment]
Understood. So here is the updated one.

![checked task creation](https://github.com/user-attachments/assets/733cc64c-796e-4b37-8044-c3bb257e72c0)

The only behavior change when the "Create More" checkbox is checked:
The modal should not close when "Create" is clicked.
The form should reset so the user can quickly create another task.
When the "Create More" checkbox is not checked, the modal should close after submission.

Please ignore the extra fields, they're there just for the demo.

**Comment by Balastrong** [comment]
Sound great, yes!

Let's discuss one last tiny detail, do you think the checkbox should be above the create button or next to it?
I think if it's above it might bet mistaken with something that is inside the form and still belongs to the task, while in fact it's just an extra control to the task submission.

Anyway I think we have a plan, feel free to work on it and submit a PR. If we have further details we can discuss them there ;)

**Comment by Balastrong** [comment]
Done in #48
